### ISSUE TITLE
no gpu usage

### ISSUE THREAD

**Issue by shredward70** [vertcoin-project/one-click-miner-vnext#114]
one click miner is on and i have started the mining but my GPU power never goes up like it usually does

it usually goes to 99-100 gpu usage but im getting 10% and its not even from the 1 click miner

close and restart one click miner and repoen it along with task manager

got it from githib

windows 10 and a NVIDIA RTX GPU

**Comment by gertjaap** [comment]
Verthash is not compute bound but I/O bound. Your GPU processing units will not be fully used, it's a consequence of Verthash's design and is meant to be like that.

**Comment by greg-fischer** [comment]
Being more I/o bound, I assume my drives should be hammered then, right? And then I'd assume having NVMe or fast RAID IO would help the rate, correct? Or is it network IO?  Because I'm not seeing hardly any resources used. Memory is only slightly higher, GPU barely used and GPU memory barely used. (I think it may go up a GB or so).  And the drives have almost no usage.   But my rate on an RX580 is showing about 400kh/s. If that's about right, then cool deal. :)  I was just wondering because it looks like my system is practically idle, but if that's how OCM should be working, thats cool.

**Comment by greg-fischer** [comment]
Sorry. Just noticed that in the AMD software its showing 100% GPU utilization and about 20% VRAM used.  So it is working!  If anyone runs into this, the Windows task manager doesn't match up at all, except the VRAM, looks like very little is working.
