### ISSUE TITLE
0.00 KH/s

### ISSUE THREAD

**Issue by cryptodad2021** [vertcoin-project/one-click-miner-vnext#140]
Loaded new version OCM. Everything loaded fine, added to exclusion for antivirus/defender.

Let run for few min, still says 
expected earnings (24 hr)
0.00 VTC (0.00 kH/s)

**Comment by vertiond** [comment]
Please paste your debug.log from %appdata%\vertcoin-ocm

**Comment by cryptodad2021** [comment]
Here is the debug log. 
its 2727 lines . Ill try adding as an attachment
[debug.log](https://github.com/vertcoin-project/one-click-miner-vnext/files/5948848/debug.log)
.

**Comment by vertiond** [comment]
This seems to be an issue with your network / router settings.

**Comment by JethroNu11** [comment]
Just wanted to share a solution I had to a similar issue to this, if you're getting 0.00 kH/s and have a Pi Hole/other adblocking services on your network. I installed and ran OCM with no errors, just the lack of actual mining- turns out that the domain that P2Pool uses (p2p-usa.xyz) was being blocked, so I changed to Suprnova and it's been working fine since then.
