### ISSUE TITLE
Runtime error: Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 4peman** [vertcoin-project/one-click-miner-vnext#141]
OCM randomly crashes while in the background.

Windows 10, AMD rx480

I've had this happen twice now, once on an older rc (forgot which one) and once in rc12. The crash seems somewhat random and I can not trigger it myself.

Given the log it looks like a crash in the webviewer of go itself but I'm no go export. See logs for crash information.

OCM Version: rc12-release-Windows https://github.com/vertcoin-project/one-click-miner-vnext/releases/download/2.0-rc12/vertcoin-ocm-2.0-rc12-windows-x64.zip

```
2021/02/08 10:04:23.361175 [DEBUG] Device IDX: 0
2021/02/08 10:04:27.449126 [DEBUG] [VerthashMiner] [2021-02-08 10:04:27] INFO  cl_device(0): hashrate: 352.02 kH/s
2021/02/08 10:04:27.449126 [DEBUG] Device IDX: 0
2021/02/08 10:04:31.547868 [DEBUG] [VerthashMiner] [2021-02-08 10:04:31] INFO  cl_device(0): hashrate: 352.08 kH/s
2021/02/08 10:04:31.547868 [DEBUG] Device IDX: 0
2021/02/08 10:04:32.226521 [DEBUG] [VerthashMiner] [2021-02-08 10:04:32] INFO  Stratum difficulty set to 4
2021/02/08 10:04:32.228513 [DEBUG] [VerthashMiner] [2021-02-08 10:04:32] INFO  Verthash block: 1505492
2021/02/08 10:04:35.229211 [DEBUG] [VerthashMiner] [2021-02-08 10:04:35] INFO  Stratum difficulty set to 4
2021/02/08 10:04:35.237194 [DEBUG] [VerthashMiner] [2021-02-08 10:04:35] INFO  Verthash block: 1505492
2021/02/08 10:04:35.635649 [DEBUG] [VerthashMiner] [2021-02-08 10:04:35] INFO  cl_device(0): hashrate: 352.43 kH/s
2021/02/08 10:04:35.635649 [DEBUG] Device IDX: 0
2021/02/08 10:04:38.455106 [ERROR] runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xac7180, 0xc000006170, 0x442)
        c:/go/src/runtime/debug/stack.go:24 +0xa5
main.main.func1()
        C:/src/one-click-miner-vnext/main.go:29 +0x18b
panic(0x7d0c00, 0x751f50)
        c:/go/src/runtime/panic.go:969 +0x1c7
github.com/wailsapp/wails/lib/renderer/webview._webviewDispatchGoCallback(0x364e)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.go:356 +0xc1
github.com/wailsapp/wails/lib/renderer/webview._cgoexpwrap_d1ad623198bc__webviewDispatchGoCallback(0x364e)
        _cgo_gotypes.go:301 +0x32
github.com/wailsapp/wails/lib/renderer/webview._Cfunc_CgoWebViewLoop(0x1e532ca6000, 0x1e500000001, 0x0)
        _cgo_gotypes.go:174 +0x54
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Loop.func1(0xc000248080, 0x1, 0xc000000000)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.go:279 +0x65
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Loop(0xc000248080, 0x1, 0x1)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.go:279 +0x3b
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Run(0xc000248080)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview/webview.go:283 +0x37
github.com/wailsapp/wails/lib/renderer.(*WebView).Run(0xc0001a80c0, 0xad6f80, 0xc0001a80c0)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/lib/renderer/webview.go:232 +0x1ce
github.com/wailsapp/wails.(*App).start(0xc0000e4180, 0x0, 0x0)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/app.go:145 +0x5ab
github.com/wailsapp/wails.(*App).Run(0xc0000e4180, 0x84f1e0, 0xc000050000)
        C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.9.1/app.go:93 +0xba
main.main()
        C:/src/one-click-miner-vnext/main.go:91 +0x72a
```

**Comment by vertiond** [comment]
I think this is related to having a previous running instance of VerthashMiner.exe running.  Related to https://github.com/vertcoin-project/one-click-miner-vnext/issues/155

**Comment by vertiond** [comment]
It seems that the VerthashMiner process doesn't always finish upon close.

**Comment by C-Lodder** [comment]
Only way I've managed to recitify the issue is by ending the `VerthashMiner` in Window Task Manager

**Comment by MessiahMozgus** [comment]
This is happening to me many times per day now. OCM vanishes but verthashminer.exe remains in taskmanager, and apparently is still mining to the pool just fine. But I have to crash it in taskmanager in order to get OCM to run again, or else it complains that the verthashminer is in use, obviously.

`2021/03/09 21:51:30.890455 [DEBUG] [VerthashMiner] [2021-03-09 21:51:30] INFO  cu_device(0): temp:60C, power:64W, fan:20%, hashrate: 276.04 kH/s
2021/03/09 21:51:31.735359 [DEBUG] [VerthashMiner] [2021-03-09 21:51:31] INFO  accepted: 1571/1605 (97.88%), total hashrate: 730.76 kH/s
2021/03/09 21:51:33.802625 [DEBUG] [VerthashMiner] [2021-03-09 21:51:33] INFO  cu_device(1): temp:65C, power:96W, fan:20%, hashrate: 454.68 kH/s
2021/03/09 21:51:34.628246 [ERROR] runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xda8160, 0xc0004784d8, 0x442)
	c:/go/src/runtime/debug/stack.go:24 +0xa5
main.main.func1()
	C:/src/one-click-miner-vnext/main.go:29 +0x18b
panic(0xab09a0, 0xa31fb0)
	c:/go/src/runtime/panic.go:969 +0x1c7
github.com/wailsapp/wails/lib/renderer/webview._webviewDispatchGoCallback(0x9d6f)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.11.0/lib/renderer/webview/webview.go:356 +0xc1
github.com/wailsapp/wails/lib/renderer/webview._cgoexpwrap_d1ad623198bc__webviewDispatchGoCallback(0x9d6f)
	_cgo_gotypes.go:301 +0x32
github.com/wailsapp/wails/lib/renderer/webview._Cfunc_CgoWebViewLoop(0x2a0f0e65f10, 0x2a000000001, 0x0)
	_cgo_gotypes.go:174 +0x54
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Loop.func1(0xc000006070, 0xc000000001, 0xc000000000)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.11.0/lib/renderer/webview/webview.go:279 +0x65
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Loop(0xc000006070, 0x1, 0x1)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.11.0/lib/renderer/webview/webview.go:279 +0x3b
github.com/wailsapp/wails/lib/renderer/webview.(*webview).Run(0xc000006070)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.11.0/lib/renderer/webview/webview.go:283 +0x37
github.com/wailsapp/wails/lib/renderer.(*WebView).Run(0xc000684540, 0xdb7ec0, 0xc000684540)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.11.0/lib/renderer/webview.go:232 +0x1ce
github.com/wailsapp/wails.(*App).start(0xc0001ce080, 0x0, 0x0)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.11.0/app.go:145 +0x5ab
github.com/wailsapp/wails.(*App).Run(0xc0001ce080, 0xb2eec0, 0xc0001c8000)
	C:/Users/build/go/pkg/mod/github.com/wailsapp/wails@v1.11.0/app.go:93 +0xba
main.main()
	C:/src/one-click-miner-vnext/main.go:90 +0x6ae
`

**Comment by vertiond** [comment]
A user having a recurring problem with OCM randomly crashing and still mining int he background was able to solve it by changing the screen settings to never go to sleep in Power Settings.

**Comment by MessiahMozgus** [comment]
Yeah I have a monitor with a displayport connection which, when I turn the monitor off, it eventually will act as if the monitor has been disconnected. I suspect this is the point at which OCM vanishes. It also plagues me when streaming gaming to my livingroom nvidia shield if my monitor is off, because the display will break after a while. The solution is to use HDMI instead of displayport, the displayport connection forces what is known as deep sleep.

I'm gonna start switching the desktop to an HDMI connection prior to leaving for the day and seeing if this keeps OCM running. I suspect it will.

**Comment by KforG** [comment]
This issues was very prevalent around the time this issue was created, but have anyone experienced these crashes in later versions? Or can this issue be assumed solved?

**Comment by vertiond** [comment]
Yeah I feel like it got fixed somehow by updating wails
