### ISSUE TITLE
Wacatac trojan

### ISSUE THREAD

**Issue by DukeNukem-dev** [vertcoin-project/one-click-miner-vnext#153]
Downloaded the latest version (vertcoin-ocm-2.0-rc13-windows-x64.zip) and ran the application.

Windows Defender blocks it 

Threat detected: Trojan:Win32/Wacatac.D8!ml
Alert Level: Severe
Date: 15/02/2021 12:36 PM
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Affected Items:
file: C:\Users\hassa\AppData\Local\Temp\Rar$EXa11476.28595\vertcoin-ocm.exe

![image](https://user-images.githubusercontent.com/54203477/107897364-f74c2800-6f8c-11eb-8414-956a02176a82.png)

**Comment by Alvie** [comment]
It's a false alarm, mining software commonly gets flagged as a virus/Trojan because sometimes other apps include miners in the background without the user noticing.

The antivirus cannot distinguish between what is a miner and what is a malicious app that mines in the background.

If you are so concerned, you can verify the code on the GitHub: https://github.com/vertcoin-project/one-click-miner-vnext and also you may want to build it yourself from scratch if you don't trust the source.
