### ISSUE TITLE
 identified as a virus

### ISSUE THREAD

**Issue by cortexuvula** [vertcoin-project/one-click-miner-vnext#173]
windows 10 antivirus software identified 1 click miner(vertcoin-ocm-2.0-rc13-windows-x64\vertcoin-ocm.exe) as a virus - Program:Win32/Contebrew.A!ml

**Comment by vertiond** [comment]
Mining software commonly gets flagged as a virus/Trojan because sometimes other apps include miners in the background without the user noticing.

The antivirus cannot distinguish between what is a miner and what is a malicious app that mines in the background.

You can verify the code of OCM as well as the [upstream miner](https://github.com/CryptoGraphics/VerthashMiner) and build from source to verify authenticity.
