### ISSUE TITLE
Windows Trojan warning and file delete

### ISSUE THREAD

**Issue by varchar32** [vertcoin-project/one-click-miner-vnext#184]
Right after download of Windows zip version it gets a severe warning;
Trojan:Win32/Wacatac.D8!ml
![image](https://user-images.githubusercontent.com/79290217/108438668-c171a280-721d-11eb-8d36-5749a83ab67e.png)

**Comment by ricedana** [comment]
Same e problem. This is a serious issue that needs resolved

**Comment by Meowdance** [comment]
Yeah, I think this must be a Windows update as I'd been running One Click Miner with zero issues prior to last night. Overnight the current and previous versions of OCM on my machine have all been auto deleted by Windows Security.

**Comment by vertiond** [comment]
Mining software commonly gets flagged as a virus/Trojan because sometimes other apps include miners in the background without the user noticing.

The antivirus cannot distinguish between what is a miner and what is a malicious app that mines in the background.

You can verify the code of OCM as well as the [upstream miner](https://github.com/CryptoGraphics/VerthashMiner) and build from source to verify authenticity.

@Meowdance You may need to add an exclusion to your antivirus / Windows Defender.
