### ISSUE TITLE
0 VTC at spendable balance

### ISSUE THREAD

**Issue by alenalbrecht** [vertcoin-project/one-click-miner-vnext#240]
Hi all.
I just lost ove 19 VTC ! 
Restarted pc normal and got 0 on spendable balance
http://prntscr.com/10essvw
Also miner shows inf VTC earning.
Will I be refunded?
I didnt transfered them to wallet or got any warning at all!

Thank you,
Br 
Alen

**Comment by oakman420** [comment]
same with me all coins gone wtf  i had lots vanished id vertcoin down on one computer it says no compatible minors

**Comment by benpls1** [comment]
same nightmare :'(

**Comment by kensagle** [comment]
Same here, tried to send payout to avoid what others were posting about lost coins.  Xfer to wallet failed, then I restarted mining and balance gone.  Didn't lose much, but this needs to not be taken lightly.  This is a really big mistake/bug and will push many away from using the OCM and possibly VTC in general.  Others have lost a lot more than me on this.  I will now be moving my GPU to other software/coins at least for a while if not permanently.  Trust is hard to obtain and easy to lose.

**Comment by mv1gaming12** [comment]
> 
> 
> "This is a really big mistake/bug and will push many away from using the OCM and possibly VTC in general."

I'm that upset I've gone straight back to mining ETH, this is a joke!
I feel really bad for everyone.

**Comment by oakman420** [comment]
Nooooooooo I had so much so upset about this

Sent from my iPhone

On Mar 6, 2021, at 7:55 PM, mv1gaming12 <notifications@github.com> wrote:

﻿

"This is a really big mistake/bug and will push many away from using the OCM and possibly VTC in general."

I'm that upset I've gone straight back to mining ETH, this is a joke!
I feel really bad for everyone.

**Comment by C-Lodder** [comment]
Seems to have been resolved now

**Comment by oakman420** [comment]
Yessssssss I have my coins but my one computer still says no compatible GPU and I do have them and they are working

Sent from my iPhone

On Mar 6, 2021, at 11:19 PM, Lodder <notifications@github.com> wrote:

﻿

Seems to have been resolved now

**Comment by vertiond** [comment]
The OCM showed an incorrect (zero) balance and ~Inf estimated earnings due to the OCM Backend being unreachable. There was an error in the DNS configuration for the domain. The configuration is restored, and according to https://www.whatsmydns.net/#A/ocm-backend.blkidx.org it's been propagated. But it could take time to propagate to your ISP (up to 24h). 

If you need access immediately and it doesn't work for you yet, the work around is to add a hosts file entry for ocm-backend.blkidx.org with the IP address 90.145.218.243  Here's how to: https://linuxize.com/post/how-to-edit-your-hosts-file/
