### ISSUE TITLE
vert coin gone on both my pc is there maintenance going on will i get my coins back i had lots ?

### ISSUE THREAD

**Issue by oakman420** [vertcoin-project/one-click-miner-vnext#241]

**Comment by alenalbrecht** [comment]
lost like 19.something on Zergpool dont know how?

**Comment by benpls1** [comment]
I lost all mine :'( I was waiting for the next payout before transferring... shit

**Comment by oakman420** [comment]
fucking dumb and now mine says no miner and i have good gpu

**Comment by lizrdmen420** [comment]
I lost my coins as well last night. this was only a test for me but still had coins an now theyre gone.

**Comment by mv1gaming12** [comment]
This morning I had 10 VTC paid out.
Came back later, it was 0...
Says INF -+.

I don't know what's going on laetly but there is a lot of issues!

**Comment by vertiond** [comment]
The OCM showed an incorrect (zero) balance and ~Inf estimated earnings due to the OCM Backend being unreachable. There was an error in the DNS configuration for the domain. The configuration is restored, and according to https://www.whatsmydns.net/#A/ocm-backend.blkidx.org it's been propagated. But it could take time to propagate to your ISP (up to 24h). 

If you need access immediately and it doesn't work for you yet, the work around is to add a hosts file entry for ocm-backend.blkidx.org with the IP address 90.145.218.243  Here's how to: https://linuxize.com/post/how-to-edit-your-hosts-file/
