### ISSUE TITLE
Vertcoin one click miner

### ISSUE THREAD

**Issue by lizrdmen420** [vertcoin-project/one-click-miner-vnext#242]
missing coins
 i expected my coins in wallet to be there next day.

 My coins disappeared the next day.

 I'm not willing to try at this time.

 vertcoin-ocm-2.0-windows-x64-debug

alienware r3

 na

 i followed the instructions and started mining.

 I'm not sure what happened. The coins were in the wallet. Please advise. Thank you.

**Comment by vertiond** [comment]
The OCM showed an incorrect (zero) balance and ~Inf estimated earnings due to the OCM Backend being unreachable. There was an error in the DNS configuration for the domain. The configuration is restored, and according to https://www.whatsmydns.net/#A/ocm-backend.blkidx.org it's been propagated. But it could take time to propagate to your ISP (up to 24h). 

If you need access immediately and it doesn't work for you yet, the work around is to add a hosts file entry for ocm-backend.blkidx.org with the IP address 90.145.218.243  Here's how to: https://linuxize.com/post/how-to-edit-your-hosts-file/
