### ISSUE TITLE
INF and NaN issue and zero balance

### ISSUE THREAD

**Issue by cezarjrv** [vertcoin-project/one-click-miner-vnext#244]
Inf and Nan issue, balance become zero
 it should run  with no problem because the OCM is a latest version

vertcoin-ocm final
![Capture](https://user-images.githubusercontent.com/34861451/110230837-b2456100-7f4e-11eb-8b2c-efe81df8117c.JPG)
![Capture](https://user-images.githubusercontent.com/34861451/110230846-bffae680-7f4e-11eb-8e6e-f588d664fd18.JPG)

-2.0-windows-x64

 windows 7 64bit/ Rx470 4gb

**Comment by C-Lodder** [comment]
Same issue for me.
Started last night

Win 10 / GXT 1070

**Comment by C-Lodder** [comment]
Seems to have been resolved now

**Comment by vertiond** [comment]
The OCM showed an incorrect (zero) balance and ~Inf estimated earnings due to the OCM Backend being unreachable. There was an error in the DNS configuration for the domain. The configuration is restored, and according to https://www.whatsmydns.net/#A/ocm-backend.blkidx.org it's been propagated. But it could take time to propagate to your ISP (up to 24h). 

If you need access immediately and it doesn't work for you yet, the work around is to add a hosts file entry for ocm-backend.blkidx.org with the IP address 90.145.218.243  Here's how to: https://linuxize.com/post/how-to-edit-your-hosts-file/

**Comment by cezarjrv** [comment]
Thank you so much.
