### ISSUE TITLE
VerthashMiner.exe treated as virus

### ISSUE THREAD

**Issue by 32x0lf** [vertcoin-project/one-click-miner-vnext#262]
![image](https://user-images.githubusercontent.com/21064877/111880641-a7c3a680-89e7-11eb-8d9f-418aa39a03e9.png)
I scan it to virustotal and  this is the result

![image](https://user-images.githubusercontent.com/21064877/111880656-bf9b2a80-89e7-11eb-9848-2e748105b34e.png)

 - vNext 2.0 Final

- Windows 10 Pro

**Comment by vertiond** [comment]
The Checks failed: Access is denied error usually results from having a previous running instance of VerthashMiner.exe running in Task Manager.  You must find and kill it. Alternatively, restart your computer.  A user having a recurring problem with this was able to solve it by changing the screen settings to never go to sleep in Power Settings.

Mining software commonly gets flagged as a virus/Trojan because sometimes other apps include miners in the background without the user noticing.

The antivirus cannot distinguish between what is a miner and what is a malicious app that mines in the background.

You can verify the code of OCM as well as the [upstream miner](https://github.com/CryptoGraphics/VerthashMiner) and build from source to verify authenticity.
