### ISSUE TITLE
BE CAREFUL

### ISSUE THREAD

**Issue by socket23** [vertcoin-project/one-click-miner-vnext#281]
there is a version out there that contains a real virus.

**Comment by vertiond** [comment]
Mining software commonly gets flagged as a virus/Trojan because sometimes other apps include miners in the background without the user noticing.

The antivirus cannot distinguish between what is a miner and what is a malicious app that mines in the background.

You can verify the code of OCM as well as the upstream miner and build from source to verify authenticity.
