### ISSUE TITLE
v2.1-beta Checks failed Miner software no software compatible GPUs found.  I removed the NVIDIA Geforce drivers and removed virus scan and still says this check fail.  Was working prior to uploading GPU drivers. Please advise bet 

### ISSUE THREAD

**Issue by mig2024** [vertcoin-project/one-click-miner-vnext#329]

**Comment by gertjaap** [comment]
If you actually removed the nvidia geforce drivers that's most likely the cause. You would need the latest version of the nvidia drivers installed and loaded in order to properly work with any GPU mining software. 

If the problem persists could you please add screenshots or debug logs (located in %APPDATA%\vertcoin-ocm) for further analysis.

**Comment by Migz93** [comment]
I set a friend of mine up with OCM and he's having the same/similar error.
It was running fine for him for about a month and then maybe a week or so ago (Around the same time as a GPU driver update) his OCM started giving him the error message "Miner software reported no compatible GPUs".

I've just had him upgrade to the latest beta 2 with no change.
I've grabbed a copy of his debug logs and uploaded here
https://pastebin.com/AKS4sXzm

Let me know if theres anything else I can grab from him.
Personally my OCM is still working fine with the same GPU drivers, albeit everything else PC hardware wise is different between the two of us.
