### ISSUE TITLE
The software is a spy  and a virus ...   dont download teh software "vertcoin-ocm-2.1-beta4-windows-x64"

### ISSUE THREAD

**Issue by ilidan23** [vertcoin-project/one-click-miner-vnext#461]

**Comment by Alvie** [comment]
What makes you think it's a virus? If you don't trust the provided binaries you can read through the source code and compile it yourself.

Some anti-virus applications incorrectly flag it as malware as it is a miner and contains mining software. This is because other programs that actually are malware, sometimes mine in the background without the user knowing. In those sort of apps, the miner is hidden within the application, so anti-virus applications classify them as "Trojans". This leads to applications that are also intended for mining to be flagged as the anti virus applications cannot tell the difference between a hidden miner and a visible miner.

Again, if you have any doubts, the one click miner is fully open source and the mining software that it uses (VerthashMiner) is also fully open source, so you can read through the code to verify it and compile it yourself if you don't trust the developers who signed it.
