### ISSUE TITLE
Can't send coins from wallet

### ISSUE THREAD

**Issue by Moldytzu** [vertcoin-project/one-click-miner-vnext#486]
When I click on "Send coins" and I paste wallet's address and I key in my password, I get a "Failed to send you coins sending.backend_failure" error message.

To send my coins to my wallet.

![image](https://user-images.githubusercontent.com/40271862/158378954-49f4fa04-773b-4ed8-b68e-88c77b3c06ba.png)

Download lastest beta release, mine, try to send the coins.

https://github.com/vertcoin-project/one-click-miner-vnext/releases/download/2.1-beta4/vertcoin-ocm-2.1-beta4-windows-x64.zip

NVidia Geforce 1050 Ti, Windows 10 Professional 21h1 build 19043.1566

![image](https://user-images.githubusercontent.com/40271862/158379322-a7d6c199-63c4-4ef1-8e83-de579069c311.png)
the settings window

**Comment by KforG** [comment]
One of the backend servers was down at the time you created this issue. This might be the cause.

Check if the transaction went through anyway, you can use [this](https://insight.vertcoin.org/) block explorer if you don't have access to the wallet or similar, input your wallet address (Copy it from the symbol next to VTC), and look for an outgoing transaction.

**Comment by solar1pv** [comment]
I have the same problem.  
I have two computers, and one works perfect every time and the other one is giving me the same problem for the last two weeks. 
The one that works great is Windows 7 with a older version of VTC over a year old. 
The one with this problem is Windows 10 Pro, with a newer version of VTC that we started a month ago. 
Thank you, 
Robert & Elena
