### ISSUE TITLE
Error occurred on the script on this page

### ISSUE THREAD

**Issue by adamcollier1** [vertcoin-project/one-click-miner-vnext#55]
<img width="818" alt="Screenshot 2019-08-07 at 19 12 55" src="https://user-images.githubusercontent.com/35997054/62647097-b7dc5e80-b947-11e9-9f46-b84e9b9adf01.png">

Happens whilst start / stopping mining

or also when changing a setting and pressing save.

Happens very often on windows 10

**Comment by antopib** [comment]
i have the same problem

**Comment by gertjaap** [comment]
I was incorrectly referencing the translation component in a few places. I think this is fixed with https://github.com/vertcoin-project/one-click-miner-vnext/commit/d6d423933dcb10cb52e32a15a33df966cacf94c9 - Please reopen the issue if it still occurs. I can make a debug build that outputs more logging (specifically script errors) which might be helpful.

**Comment by adamcollier1** [comment]
Just ran RC2 for the first time in a while.. getting the same error.. It was when i checked the "use closed source miners" box

![image](https://user-images.githubusercontent.com/35997054/78512316-784a6880-779b-11ea-89bb-abe98efa9e2f.png)
