### ISSUE TITLE
Checks failed:  No compatible GPUs detected

### ISSUE THREAD

**Issue by WhitG** [vertcoin-project/one-click-miner-vnext#74]
Checks failed:  No compatible GPUs detected
![image](https://user-images.githubusercontent.com/26853422/75352505-796ca980-586f-11ea-9aaf-97c610ffc229.png)

Was hoping to download the One Click miner and start mining 

I was able to download it.  However, once I open it, I get the error message. "Checks failed:  No compatible GPUs detected"

It happens every time.  I just download, try to open and it happens

vertcoin-ocm-1.0-rc1-windows-x64.zip

 I have the following computer:  HP Pavilion 570-p026 Desktop (Intel Core i5, 1TB HDD, 12GB RAM, Windows 10, Intel HD 630 Graphics)

I have no idea.  Is this relevant to my system? I really don't know.  I'm not a super technical computer guy, but learning a little more each day.

**Comment by gertjaap** [comment]
Intel HD 630 Graphics cards are not capable of mining. They're not powerful enough, and therefore no one developed miner software for it. The only cards powerful enough are the higher end NVidia and AMD cards, which is why miner software only exist for those two hardware vendors.

Sorry to have to disappoint you, but it will not work on your system unless you install an upgraded graphics card.

**Comment by WhitG** [comment]
That's okay, Gert.  I appreciate you for looking into this.  I might buy a higher end graphics card at some point, but will probably just stick to trading.  Tipping you a little BAT for your assistance.
