### ISSUE TITLE
Miner says my gpu is not compatible 

### ISSUE THREAD

**Issue by lolpop9009** [vertcoin-project/one-click-miner-vnext#78]
I have a RX 560, i just need help trying to run this
I am new to mining in general 
![vtc](https://user-images.githubusercontent.com/63620027/79170589-b56ab800-7da4-11ea-8d25-7d16d4c7e206.png)
I mean i don't know what else to say, other then i am on windows 10

**Comment by gertjaap** [comment]
Fixed in https://github.com/vertcoin-project/one-click-miner-vnext/commit/c182a96dc049b7ac416eaeb0909aa55114048dcd

You can download release https://github.com/vertcoin-project/one-click-miner-vnext/releases/tag/1.0.1 to test it out.

**Comment by gertjaap** [comment]
@lolpop9009 could you confirm this is working for you now. If not you can also try the new 2.0 alpha version - it should be working even better at detecting GPUs since it relies on the underlying miner binaries to do so.

If you still have trouble getting your GPU properly detected, feel free to post your debug.log (it's in `%APPDATA%\vertcoin-ocm` on Windows) and reopen the issue.
