### ISSUE TITLE
ocm is not working

### ISSUE THREAD

**Issue by adelakhavan** [vertcoin-project/one-click-miner-vnext#89]
I have an alienware laptop with a nvidia GTX970M. I tried the one click miner but not recognizing my GPU and when I use vertcoin one click miner also I am unable to connect to P2Pool network.

I am working on windows 8 platform

**Comment by gertjaap** [comment]
this version of the OCM does not include P2Pool, are you using an older version? Please try with the latest version, it should properly detect mobile GPUs as well - even though I would recommend against mining continuously on a laptop due to potential overheating. 

If you still fail to run on the latest version of the OCM (2.0 beta 6 at the time of writing this), then please post the `debug.log` which you can find in `%APPDATA%\vertcoin-ocm` and reopen the issue
